- integration-tests/src/test/groovy/uk/gov/justice/digital/hmpps/cattool/specs/HomePageSpecification.groovy
- server/services/offendersService.js
- server/views/pages/index.html
- test/services/offenderService.test.js
Just needed column title change and use of business days
> DC-92 Add 'days since sentence' to list of prisoners that need categorising

- integration-tests/src/test/groovy/uk/gov/justice/digital/hmpps/cattool/model/TestFixture.groovy
- integration-tests/src/test/groovy/uk/gov/justice/digital/hmpps/cattool/pages/CategoriserTasklistPage.groovy
- integration-tests/src/test/groovy/uk/gov/justice/digital/hmpps/cattool/specs/SecurityInputSpecification.groovy
- server/data/formClient.js
- server/services/formService.js
- server/services/offendersService.js
- server/views/pages/securityHome.html
mostly tidying changes in a 2nd commit
> Dc 97 security teams review list

- integration-tests/src/test/groovy/uk/gov/justice/digital/hmpps/cattool/pages/ExtremismPage.groovy
- integration-tests/src/test/groovy/uk/gov/justice/digital/hmpps/cattool/pages/ReviewPage.groovy
- integration-tests/src/test/groovy/uk/gov/justice/digital/hmpps/cattool/pages/SupervisorReviewPage.groovy
- integration-tests/src/test/groovy/uk/gov/justice/digital/hmpps/cattool/specs/ExtremismSpecification.groovy
- integration-tests/src/test/groovy/uk/gov/justice/digital/hmpps/cattool/specs/ProvisionalCategorySpecification.groovy
- integration-tests/src/test/groovy/uk/gov/justice/digital/hmpps/cattool/specs/ReviewSpecification.groovy
- integration-tests/src/test/groovy/uk/gov/justice/digital/hmpps/cattool/specs/SupervisorSpecification.groovy
- server/routes/form.js
- server/services/formService.js
- server/views/formPages/ratings/extremismRating.html
- server/views/formPages/ratings/violenceRating.html
- server/views/formPages/supervisor/review.html
- server/views/partials/reviewContents.html
- test/routes/form.test.js
- test/services/formService.test.js
part 1 - calculate the cat from risk profile (and ratings) data in the db json.
Ill do part 2, the bit to actually store the risk profile data (at review time) next.
> DC-142 wire-up provisional categorisation recommendation

- assets/sass/application.sass
- server/views/formPages/security/review.html
- server/views/pages/tasklist.html
... for categoriser's task list page and security review : Restore to full width
> DC-223 Cramped 2/3 width headers

- integration-tests/src/test/groovy/uk/gov/justice/digital/hmpps/cattool/pages/openConditions/EarliestReleasePage.groovy
- integration-tests/src/test/groovy/uk/gov/justice/digital/hmpps/cattool/pages/openConditions/ForeignNationalsPage.groovy
- integration-tests/src/test/groovy/uk/gov/justice/digital/hmpps/cattool/specs/OpenConditionsSpecification.groovy
- server/app.js
- server/config/openConditions.js
- server/routes/form.js
- server/routes/openConditions.js
- server/services/formService.js
- server/utils/statusEnum.js
- server/views/openConditions/earliestReleaseDate.html
- server/views/openConditions/foreignNationals.html
- server/views/pages/openConditionsNotSuitable.html
- test/routes/form.test.js
- test/services/formService.test.js
Build 'earliest release date' page
Build 'Not suitable for open conditions' page
Build 'Foreign Nationals' page in Open Conditions assessment
> DC-148, 154, 158, 150, 155

- integration-tests/src/test/groovy/uk/gov/justice/digital/hmpps/cattool/model/TestFixture.groovy
- integration-tests/src/test/groovy/uk/gov/justice/digital/hmpps/cattool/pages/ApprovedViewPage.groovy
- integration-tests/src/test/groovy/uk/gov/justice/digital/hmpps/cattool/pages/CategoriserDonePage.groovy
- integration-tests/src/test/groovy/uk/gov/justice/digital/hmpps/cattool/pages/CategoriserHomePage.groovy
- integration-tests/src/test/groovy/uk/gov/justice/digital/hmpps/cattool/pages/RecategoriserHomePage.groovy
- integration-tests/src/test/groovy/uk/gov/justice/digital/hmpps/cattool/pages/SecurityHomePage.groovy
- integration-tests/src/test/groovy/uk/gov/justice/digital/hmpps/cattool/pages/SupervisorReviewPage.groovy
- integration-tests/src/test/groovy/uk/gov/justice/digital/hmpps/cattool/pages/TasklistPage.groovy
- integration-tests/src/test/groovy/uk/gov/justice/digital/hmpps/cattool/pages/TasklistRecatPage.groovy
- integration-tests/src/test/groovy/uk/gov/justice/digital/hmpps/cattool/pages/openConditions/ProvisionalCategoryOpenPage.groovy
- integration-tests/src/test/groovy/uk/gov/justice/digital/hmpps/cattool/specs/HomePageSpecification.groovy
- integration-tests/src/test/groovy/uk/gov/justice/digital/hmpps/cattool/specs/OpenConditionsSpecification.groovy
- integration-tests/src/test/groovy/uk/gov/justice/digital/hmpps/cattool/specs/ProvisionalCategorySpecification.groovy
- integration-tests/src/test/groovy/uk/gov/justice/digital/hmpps/cattool/specs/SecurityInputSpecification.groovy
- server/routes/openConditions.js
- server/views/formPages/approvedView.html
Also Minor fix clearing empty "overridden" fields
> Additional open conditions integration tests

- assets/sass/application-ie8.sass
- integration-tests/src/test/groovy/uk/gov/justice/digital/hmpps/cattool/mockapis/Elite2Api.groovy
- integration-tests/src/test/groovy/uk/gov/justice/digital/hmpps/cattool/pages/TasklistRecatPage.groovy
- integration-tests/src/test/groovy/uk/gov/justice/digital/hmpps/cattool/specs/ApprovedViewSpecification.groovy
- integration-tests/src/test/groovy/uk/gov/justice/digital/hmpps/cattool/specs/ReviewSpecification.groovy
- integration-tests/src/test/groovy/uk/gov/justice/digital/hmpps/cattool/specs/SupervisorSpecification.groovy
- integration-tests/src/test/groovy/uk/gov/justice/digital/hmpps/cattool/specs/TasklistRecatSpecification.groovy
- integration-tests/src/test/groovy/uk/gov/justice/digital/hmpps/cattool/specs/TasklistSpecification.groovy
- integration-tests/src/test/groovy/uk/gov/justice/digital/hmpps/cattool/specs/recat/HigherSecurityReviewSpecification.groovy
- server/services/offendersService.js
- server/views/formPages/formTemplate.html
- server/views/pages/tasklistRecat.html
- server/views/partials/offenderDetails.html
- test/routes/tasklistRecat.test.js
Also an ie8 fix and recat todo list fix
> Dc 323 add content to task list page

- package-lock.json
- package.json
- server/app.js
- server/authentication/clientCredentials.js
- server/catToolSerialisers.js
- server/data/nomisClientBuilder.js
- server/data/riskProfilerClientBuilder.js
- test/data/nomisClient.test.js
- test/data/riskProfilerClient.test.js
Also add correlation id and thread-local capability
> DC-357 Approved view: Allow access to offender details for offenders who have transferred

- log.js
- server/app.js
- server/authentication/clientCredentials.js
- server/catToolSerialisers.js
- server/data/nomisClientBuilder.js
- server/data/riskProfilerClientBuilder.js
Finish off work started in DC-357
> DC-334 Add correlationID to requests

- integration-tests/src/test/groovy/uk/gov/justice/digital/hmpps/cattool/model/DatabaseUtils.groovy
- integration-tests/src/test/groovy/uk/gov/justice/digital/hmpps/cattool/model/TestFixture.groovy
- integration-tests/src/test/groovy/uk/gov/justice/digital/hmpps/cattool/specs/OpenConditionsSpecification.groovy
- integration-tests/src/test/groovy/uk/gov/justice/digital/hmpps/cattool/specs/ReviewSpecification.groovy
- integration-tests/src/test/groovy/uk/gov/justice/digital/hmpps/cattool/specs/SecuritySpecification.groovy
- integration-tests/src/test/groovy/uk/gov/justice/digital/hmpps/cattool/specs/SupervisorSpecification.groovy
- server/routes/form.js
- test/routes/form.test.js
fix initial cat supervisor review page
> CAT-327 convictions not pulled through

- integration-tests/src/test/groovy/uk/gov/justice/digital/hmpps/cattool/pages/recat/ApprovedViewRecatPage.groovy
- integration-tests/src/test/groovy/uk/gov/justice/digital/hmpps/cattool/specs/SupervisorSpecification.groovy
- integration-tests/src/test/groovy/uk/gov/justice/digital/hmpps/cattool/specs/recat/ApprovedViewSpecification.groovy
- server/routes/form.js
- server/routes/openConditions.js
- server/services/offendersService.js
- server/views/formPages/recat/approvedView.html
Add missing cat history service call and fix tests
> CAT-387 ApprovedView recat "There are no previous categorisations"

- integration-tests/src/test/groovy/uk/gov/justice/digital/hmpps/cattool/mockapis/Elite2Api.groovy
- integration-tests/src/test/groovy/uk/gov/justice/digital/hmpps/cattool/model/TestFixture.groovy
- integration-tests/src/test/groovy/uk/gov/justice/digital/hmpps/cattool/specs/recat/DecisionSpecification.groovy
- server/data/nomisClientBuilder.js
- server/services/offendersService.js
- test/services/offenderService.test.js
Separate into BCD for one call and IJ for the other.
Also include I, Js up to age 22 in the 'U21's
> CAT-401 Recat todo list - under 21s still being displayed after recat complete

- integration-tests/src/test/groovy/uk/gov/justice/digital/hmpps/cattool/mockapis/Elite2Api.groovy
- integration-tests/src/test/groovy/uk/gov/justice/digital/hmpps/cattool/specs/CategoriserDoneSpecification.groovy
- integration-tests/src/test/groovy/uk/gov/justice/digital/hmpps/cattool/specs/SupervisorSpecification.groovy
- integration-tests/src/test/groovy/uk/gov/justice/digital/hmpps/cattool/specs/recat/ApprovedViewSpecification.groovy
- integration-tests/src/test/groovy/uk/gov/justice/digital/hmpps/cattool/specs/recat/RecategoriserDoneSpecification.groovy
- server/data/nomisClientBuilder.js
- server/services/offendersService.js
- test/data/nomisClient.test.js
- test/services/offenderService.test.js
When no match in nomis, display reduced info in the cat/recat/supervisor done list
> CAT-381 Cat tool Done lists always use sequence no

- integration-tests/src/test/groovy/uk/gov/justice/digital/hmpps/cattool/mockapis/Elite2Api.groovy
- integration-tests/src/test/groovy/uk/gov/justice/digital/hmpps/cattool/specs/HomePageSpecification.groovy
- integration-tests/src/test/groovy/uk/gov/justice/digital/hmpps/cattool/specs/OpenConditionsSpecification.groovy
- integration-tests/src/test/groovy/uk/gov/justice/digital/hmpps/cattool/specs/SupervisorSpecification.groovy
- integration-tests/src/test/groovy/uk/gov/justice/digital/hmpps/cattool/specs/recat/OpenConditionsSpecification.groovy
- server/data/formClient.js
- server/services/offendersService.js
- test/data/formClient.test.js
- test/services/offenderService.test.js
Display PNOMIS instead of button if sequences dont match
> CAT-403 Categorisation identification: supervisor todo list match sequence number

- server/views/formPages/recat/awaitingApprovalView.html
- server/views/formPages/recat/prisonerBackground.html
- server/views/formPages/recat/riskAssessment.html
- server/views/partials/reviewContentsRecat.html
- test/routes/form.test.js
guidance change
question change
> open conditions missed from awaiting approval (initial cat)

- assets/sass/application.sass
- integration-tests/src/test/groovy/uk/gov/justice/digital/hmpps/cattool/mockapis/Elite2Api.groovy
- integration-tests/src/test/groovy/uk/gov/justice/digital/hmpps/cattool/pages/CategoriserHomePage.groovy
- integration-tests/src/test/groovy/uk/gov/justice/digital/hmpps/cattool/pages/recat/RecategoriserHomePage.groovy
- integration-tests/src/test/groovy/uk/gov/justice/digital/hmpps/cattool/specs/HomePageSpecification.groovy
- package-lock.json
- package.json
- server/app.js
- server/services/offendersService.js
- server/views/pages/categoriserHome.html
- server/views/pages/recategoriserHome.html
- test/services/offenderService.test.js
Slaps an 'overdue' label on relevant categorisations in the todo lists
> CAT-48 Overdue categorisations more visible

- integration-tests/src/test/groovy/uk/gov/justice/digital/hmpps/cattool/mockapis/Elite2Api.groovy
- integration-tests/src/test/groovy/uk/gov/justice/digital/hmpps/cattool/model/TestFixture.groovy
- integration-tests/src/test/groovy/uk/gov/justice/digital/hmpps/cattool/pages/CategoriserHomePage.groovy
- integration-tests/src/test/groovy/uk/gov/justice/digital/hmpps/cattool/pages/recat/RecategoriserHomePage.groovy
- integration-tests/src/test/groovy/uk/gov/justice/digital/hmpps/cattool/specs/HomePageSpecification.groovy
- integration-tests/src/test/groovy/uk/gov/justice/digital/hmpps/cattool/specs/OpenConditionsSpecification.groovy
- integration-tests/src/test/groovy/uk/gov/justice/digital/hmpps/cattool/specs/ReviewSpecification.groovy
- integration-tests/src/test/groovy/uk/gov/justice/digital/hmpps/cattool/specs/SupervisorSpecification.groovy
- integration-tests/src/test/groovy/uk/gov/justice/digital/hmpps/cattool/specs/ratings/ExtremismSpecification.groovy
- integration-tests/src/test/groovy/uk/gov/justice/digital/hmpps/cattool/specs/ratings/SecurityInputSpecification.groovy
- integration-tests/src/test/groovy/uk/gov/justice/digital/hmpps/cattool/specs/recat/OpenConditionsSpecification.groovy
- server/data/formClient.js
- server/services/offenderSort.js
- server/services/offendersService.js
- server/utils/statusEnum.js
- test/services/offenderService.test.js
1 small commit with the actual changes,
1 big one with all the test fixes!
> Cat 442 451 sorts in wrong order

- server/views/formPages/recat/decision.html
i accidently undid an earlier text change
> CAT-455 Change to category selection page - small regression

- integration-tests/src/test/groovy/uk/gov/justice/digital/hmpps/cattool/mockapis/Elite2Api.groovy
- integration-tests/src/test/groovy/uk/gov/justice/digital/hmpps/cattool/model/DatabaseUtils.groovy
- integration-tests/src/test/groovy/uk/gov/justice/digital/hmpps/cattool/pages/ApprovedViewPage.groovy
- integration-tests/src/test/groovy/uk/gov/justice/digital/hmpps/cattool/specs/ApprovedViewSpecification.groovy
- integration-tests/src/test/groovy/uk/gov/justice/digital/hmpps/cattool/specs/ProvisionalCategorySpecification.groovy
- integration-tests/src/test/groovy/uk/gov/justice/digital/hmpps/cattool/specs/SupervisorSpecification.groovy
- integration-tests/src/test/groovy/uk/gov/justice/digital/hmpps/cattool/specs/ratings/ExtremismSpecification.groovy
- integration-tests/src/test/groovy/uk/gov/justice/digital/hmpps/cattool/specs/recat/ApprovedViewSpecification.groovy
- integration-tests/src/test/groovy/uk/gov/justice/digital/hmpps/cattool/specs/recat/ReviewSpecification.groovy
- server/data/formClient.js
- server/routes/form.js
- server/routes/recat.js
- server/services/formService.js
- server/views/formPages/approvedView.html
- server/views/formPages/recat/approvedView.html
- server/views/pages/categoriserDone.html
- server/views/pages/categoriserHome.html
- server/views/pages/recategoriserDone.html
- server/views/pages/recategoriserHome.html
- server/views/pages/securityDone.html
- server/views/pages/securityHome.html
- server/views/pages/supervisorDone.html
- server/views/pages/supervisorHome.html
- test/data/formClient.test.js
- test/routes/form.test.js
- test/routes/openConditions.test.js
- test/routes/recat.test.js
- test/routes/tasklist.test.js
- test/routes/tasklistRecat.test.js
- test/services/formService.test.js
Add the sequence param, and also validate against non-existant booking id / seq combos
> Cat 491 generalise approved view old cats

- integration-tests/src/test/groovy/uk/gov/justice/digital/hmpps/cattool/model/DatabaseUtils.groovy
- integration-tests/src/test/groovy/uk/gov/justice/digital/hmpps/cattool/pages/LandingPage.groovy
- integration-tests/src/test/groovy/uk/gov/justice/digital/hmpps/cattool/pages/SecurityReferralSubmittedPage.groovy
- integration-tests/src/test/groovy/uk/gov/justice/digital/hmpps/cattool/specs/LandingPageSpecification.groovy
- integration-tests/src/test/groovy/uk/gov/justice/digital/hmpps/cattool/specs/OpenConditionsSpecification.groovy
- integration-tests/src/test/groovy/uk/gov/justice/digital/hmpps/cattool/specs/ReviewSpecification.groovy
- migrations/20190901080342_risk_change.js
- migrations/20190909000000_security_table.js
- server/data/formClient.js
- server/routes/form.js
- server/routes/home.js
- server/routes/openConditions.js
- server/routes/recat.js
- server/routes/tasklistRecat.js
- server/services/formService.js
- server/utils/functionalHelpers.js
- server/utils/routes.js
- server/utils/statusEnum.js
- server/views/pages/landing.html
- server/views/pages/securityReferralSubmitted.html
- server/views/pages/tasklist.html
- server/views/pages/tasklistRecat.html
- server/views/partials/reviewContents.html
- test/routes/home.test.js
- test/routes/tasklist.test.js
- test/routes/tasklistRecat.test.js
- test/services/formService.test.js
Actually works for initial cats too.
Needs more work to provide a confirmation page and change to a button rather than a checkbox
> CAT-375 Investigate how security can identify up and coming re-cats of interest

- integration-tests/src/test/groovy/uk/gov/justice/digital/hmpps/cattool/specs/recat/ReviewSpecification.groovy
- server/views/partials/reviewContentsRecat.html
> CAT-559 Security flagged showing as yes on recat review pages

- migrations/20191105000000_add_security_status.js
> CAT-485 Allow users to cancel a submission as long as it wasn't approved

- integration-tests/src/test/groovy/uk/gov/justice/digital/hmpps/cattool/specs/LandingPageSpecification.groovy
- integration-tests/src/test/groovy/uk/gov/justice/digital/hmpps/cattool/specs/ratings/NextReviewDateSpecification.groovy
- integration-tests/src/test/groovy/uk/gov/justice/digital/hmpps/cattool/specs/recat/NextReviewDateSpecification.groovy
- server/routes/home.js
- server/services/offendersService.js
- test/routes/form.test.js
- test/routes/home.test.js
- test/services/offenderService.test.js
consider previous cats when working out whether to do an initial or recat
> CAT-605 Cat U can cut off access to a recat in progress

- .circleci/config.yml
- integration-tests/src/test/groovy/uk/gov/justice/digital/hmpps/cattool/pages/LiteCategoriesConfirmedPage.groovy
- integration-tests/src/test/groovy/uk/gov/justice/digital/hmpps/cattool/specs/LiteSpecification.groovy
- server/app.js
- server/routes/liteCategories.js
- server/views/pages/liteApprove.html
- server/views/pages/liteCategories.html
- server/views/pages/liteCategoriesConfirmed.html
- test/routes/liteCategories.test.js
> CAT-636 UI tweaks for other categories

- gradle/wrapper/gradle-wrapper.properties
- server/authentication/clientCredentials.js
- server/authentication/signInService.js
- server/config.js
- server/data/nomisClientBuilder.js
- server/data/riskProfilerClientBuilder.js
Add the same fix that has been applied to other apps
> CAT-630 Random Timeouts - add keepalive

- helm_deploy/offender-categorisation/templates/deployment.yaml
- helm_deploy/offender-categorisation/templates/ingress.yaml
Reverts ministryofjustice/categorisation-tool#413
> Revert "DT-917: Switch out deprecated APIs"

- .circleci/config.yml
- Update files to refer to main branch instead of master
> PAT-931: Update master to main

- .circleci/config.yml
- Dockerfile
- helm_deploy/values-dev.yaml
- helm_deploy/values-preprod.yaml
- helm_deploy/values-prod.yaml
- Update circleci config to use DPS orb
- Update helm_deploy to reference quayio 
- Remove reference to AWS 2015 cert
> PAT-931: Update circle config to use DPS orbs

- .circleci/config.yml
- Pass in parameters on the deploy job to override defaults
> PAT-931: fix deploy looking in wrong helm folder

- docker-compose.yml
- Update docker-compose image reference to use new quay.io image
> PAT-931: update docker-compose image reference

- helm_deploy/offender-categorisation/templates/deployment.yaml
- helm_deploy/offender-categorisation/templates/ingress.yaml
- Update Kubernetes resource versions
> PAT-1015: Update Kubernetes resource versions

- audit-ci.json
- package.json
* This is called from the circle-ci job- scheduled nightly to identify npm security issues.
> PAT-1017: Added overnight npm security audit task

- README.md
- docker-compose.yml
- helm_deploy/values-dev.yaml
- helm_deploy/values-preprod.yaml
- helm_deploy/values-prod.yaml
- integration-tests/src/test/groovy/uk/gov/justice/digital/hmpps/cattool/specs/HealthSpecification.groovy
- package-lock.json
- package.json
- server/services/healthCheck.js
- settings.gradle
-  Update project name to offender-categorisation
> CAT-642: update project name to offender-categorisation

- integration-tests/src/test/groovy/uk/gov/justice/digital/hmpps/cattool/specs/LiteSpecification.groovy
- server/services/offendersService.js
- server/views/pages/categoriserHome.html
- server/views/pages/recategoriserHome.html
- test/routes/home.test.js
- test/services/offenderService.test.js
Added 'OTHER' label in todo lists.
> CAT-648 cat process allowed to start even when lite cat in progress

- integration-tests/src/test/groovy/uk/gov/justice/digital/hmpps/cattool/mockapis/RiskProfilerApi.groovy
- integration-tests/src/test/groovy/uk/gov/justice/digital/hmpps/cattool/specs/ReviewSpecification.groovy
- integration-tests/src/test/groovy/uk/gov/justice/digital/hmpps/cattool/specs/SupervisorSpecification.groovy
- integration-tests/src/test/groovy/uk/gov/justice/digital/hmpps/cattool/specs/ratings/ViolenceSpecification.groovy
- integration-tests/src/test/groovy/uk/gov/justice/digital/hmpps/cattool/specs/recat/ApprovedViewSpecification.groovy
- integration-tests/src/test/groovy/uk/gov/justice/digital/hmpps/cattool/specs/recat/PrisonerBackgroundSpecification.groovy
- integration-tests/src/test/groovy/uk/gov/justice/digital/hmpps/cattool/specs/recat/ReviewSpecification.groovy
- server/views/formPages/ratings/violenceRating.html
- server/views/formPages/recat/prisonerBackground.html
- server/views/partials/reviewContents.html
- server/views/partials/reviewContentsRecat.html
- test/routes/form.test.js
- test/routes/recat.test.js
Change to violence warning throughout
> CAT-650 Content Changes to the Intial cat process

- server/routes/home.js
- server/views/formPages/openConditions/riskOfHarm.html
- test/routes/home.test.js
Also CAT-651 Content Changes to the Recat process, item 4
> CAT-555 Flagging to security can block progress

- integration-tests/src/test/groovy/uk/gov/justice/digital/hmpps/cattool/pages/SupervisorMessagePage.groovy
- integration-tests/src/test/groovy/uk/gov/justice/digital/hmpps/cattool/specs/OpenConditionsSpecification.groovy
- integration-tests/src/test/groovy/uk/gov/justice/digital/hmpps/cattool/specs/SupervisorSpecification.groovy
- integration-tests/src/test/groovy/uk/gov/justice/digital/hmpps/cattool/specs/recat/OpenConditionsSpecification.groovy
- server/config/supervisor.js
- server/routes/form.js
- server/views/formPages/supervisor/confirmBack.html
- server/views/formPages/supervisor/supervisorMessage.html
Pass supervisor name back to page shown to the categoriser
> CAT-678 Show supervisor name when rejected

- server/views/partials/reviewContents.html
- server/views/partials/reviewContentsRecat.html
Reverts ministryofjustice/offender-categorisation#446
> Revert "CAT-674 Redact extremism warning from printed cat view"

- integration-tests/src/test/groovy/uk/gov/justice/digital/hmpps/cattool/model/DatabaseUtils.groovy
- integration-tests/src/test/groovy/uk/gov/justice/digital/hmpps/cattool/specs/HomePageSpecification.groovy
- integration-tests/src/test/groovy/uk/gov/justice/digital/hmpps/cattool/specs/LandingPageSpecification.groovy
- integration-tests/src/test/groovy/uk/gov/justice/digital/hmpps/cattool/specs/TasklistRecatSpecification.groovy
- server/data/formClient.js
- server/routes/tasklist.js
- server/services/formService.js
- server/services/offendersService.js
- test/services/offenderService.test.js
Now includes in-progress cases from the database as well as Nomis
> CAT-676 Cancelling a manual initial cat leaves all nomis cats inactive

- package-lock.json
- package.json
Also axios version had security issues
> Remove unused axios dependency

- package-lock.json
- package.json
- server/views/formPages/ratings/extremismRating.html
- server/views/formPages/recat/prisonerBackground.html
> Cat 679 flag pf cases to security 2

- .circleci/config.yml
- README.md
- integration-tests/build.gradle
- integration-tests/src/test/groovy/uk/gov/justice/digital/hmpps/cattool/model/DatabaseUtils.groovy
- integration-tests/src/test/groovy/uk/gov/justice/digital/hmpps/cattool/specs/EventSpecification.groovy
- server/data/formClient.js
- server/services/formService.js
- server/services/offendersService.js
- server/services/sqsService.js
- server/utils/functionalHelpers.js
- test/services/offenderService.test.js
- test/services/sqsService.test.js
Added movement event handler whcih updates 4 tables
> Cat 689 unapproved cats lost when moving prison

- server/views/partials/reviewContents.html
- server/views/partials/reviewContentsRecat.html
Reverts ministryofjustice/offender-categorisation#452 and re-applies original change
> PAT-1773 Revert "Revert "CAT-674 Redact extremism warning from printed cat view""

- docker-compose-test.yml
- integration-tests/src/test/groovy/uk/gov/justice/digital/hmpps/cattool/specs/DashboardSpecification.groovy
- server/data/statsClient.js
- server/views/pages/dashboardRecat.html
Rewritten SQL to improve efficiency
> PAT-1883 DCS - performance of dashboard setting off database CPU alerts

- .circleci/config.yml
- integration-tests/build.gradle
- package-lock.json
- server/data/allocationManagerApi.js
- server/services/offendersService.js
> PAT-1863 Update DCS Screen Query Result to list POMs

- .circleci/config.yml
- server/data/allocationManagerApi.js
- test/data/allocationManagerApi.test.js
> Pat 1863 update dcs screen query result to list POMS

- package-lock.json
🤖 PAT-2140: Fix Security Vulnerabilities
> 🤖 PAT-2140: Fix Security Vulnerabilities

- integration-tests/src/test/groovy/uk/gov/justice/digital/hmpps/cattool/model/TestFixture.groovy
- integration-tests/src/test/groovy/uk/gov/justice/digital/hmpps/cattool/specs/SupervisorSpecification.groovy
- integration-tests/src/test/groovy/uk/gov/justice/digital/hmpps/cattool/specs/recat/OpenConditionsSpecification.groovy
- integration-tests/src/test/groovy/uk/gov/justice/digital/hmpps/cattool/specs/recat/ReviewSpecification.groovy
- server/config/recat.js
- server/routes/recat.js
- server/views/formPages/recat/oasysInput.html
- server/views/formPages/recat/prisonerBackground.html
- server/views/pages/tasklistRecat.html
- amend tasklistRecat.html
- amend integration tests
- fix bug validation message on oasysInput.html
> CAT-1135 add oasys to tasklist

- integration-tests/src/test/groovy/uk/gov/justice/digital/hmpps/cattool/specs/OpenConditionsSpecification.groovy
- integration-tests/src/test/groovy/uk/gov/justice/digital/hmpps/cattool/specs/recat/OpenConditionsSpecification.groovy
- integration-tests/src/test/groovy/uk/gov/justice/digital/hmpps/cattool/specs/recat/ReviewSpecification.groovy
- server/views/macros/formatAnswer.html
- server/views/partials/reviewContentsRecat.html
- add oasys content to reviewContentsRecat.html
- add macro to display text properly
> cat-1137 add oasys to cya

- integration-tests/src/test/groovy/uk/gov/justice/digital/hmpps/cattool/model/TestFixture.groovy
- integration-tests/src/test/groovy/uk/gov/justice/digital/hmpps/cattool/specs/SupervisorSpecification.groovy
- integration-tests/src/test/groovy/uk/gov/justice/digital/hmpps/cattool/specs/recat/OpenConditionsSpecification.groovy
- integration-tests/src/test/groovy/uk/gov/justice/digital/hmpps/cattool/specs/recat/ReviewSpecification.groovy
- server/config/recat.js
- server/routes/recat.js
- server/views/formPages/recat/oasysInput.html
- server/views/partials/reviewContentsRecat.html
-change oasysInput.html
-change oasysHighlightedRisks to oasysRelevantInfo 
-fix content on partial
> cat-1194 change oasys page content

- integration-tests/src/test/groovy/uk/gov/justice/digital/hmpps/cattool/model/TestFixture.groovy
- integration-tests/src/test/groovy/uk/gov/justice/digital/hmpps/cattool/pages/recat/SecurityInputPage.groovy
- integration-tests/src/test/groovy/uk/gov/justice/digital/hmpps/cattool/specs/SupervisorSpecification.groovy
- integration-tests/src/test/groovy/uk/gov/justice/digital/hmpps/cattool/specs/recat/OpenConditionsSpecification.groovy
- integration-tests/src/test/groovy/uk/gov/justice/digital/hmpps/cattool/specs/recat/ReviewSpecification.groovy
- integration-tests/src/test/groovy/uk/gov/justice/digital/hmpps/cattool/specs/recat/SecurityInputSpecification.groovy
- server/config/recat.js
- server/routes/recat.js
- server/views/formPages/recat/securityInput.html
- server/views/pages/tasklistRecat.html
- fix bug where on releoad data not correct
- made content changes as per the ticket
> cat-1158 security input content changes

- database_backup/02-cronjob.yaml
- database_refresh/02-cronjob.yaml
- update cron jobs to be cleared every 4 days.
- update cron job to use latest k8 version
> cat-1318 update cron jobs

- integration-tests/src/test/groovy/uk/gov/justice/digital/hmpps/cattool/specs/recat/FasttrackCSpecification.groovy
- server/routes/tasklistRecat.js
- test/routes/tasklistRecat.test.js
Reverts ministryofjustice/offender-categorisation#606
> Revert "cat-1340 disable fast track"

- server/routes/form.js
- server/views/formPages/ratings/securityBack.html
- server/views/pages/tasklist.html
- server/views/partials/reviewContents.html
CAT-1266 CAT-B question not asked on women's security, CYA and approval pages
> CAT-1266 modified so CAT-B not asked on womens security page

- .circleci/config.yml
- database_refresh/01-configmap-refresh-script.yaml
- database_refresh/02-cronjob.yaml
- database_refresh/adhoc-db-refresh-job.yaml
CAT-1401 update postgres version to 14.3
> CAT-1401 update postgres version to 14.3

- integration-tests/src/test/groovy/uk/gov/justice/digital/hmpps/cattool/specs/OpenConditionsSpecification.groovy
- integration-tests/src/test/groovy/uk/gov/justice/digital/hmpps/cattool/specs/ProvisionalCategorySpecification.groovy
- integration-tests/src/test/groovy/uk/gov/justice/digital/hmpps/cattool/specs/recat/ApprovedViewSpecification.groovy
- integration-tests/src/test/groovy/uk/gov/justice/digital/hmpps/cattool/specs/recat/OpenConditionsSpecification.groovy
- server/routes/form.js
- server/routes/recat.js
- server/services/formService.js
- server/views/formPages/categoriser/awaitingApprovalView.html
- server/views/formPages/openConditions/provisionalCategory.html
- server/views/formPages/recat/approvedView.html
- server/views/formPages/recat/awaitingApprovalView.html
- server/views/formPages/recat/decision.html
- server/views/partials/reviewContentsRecat.html
- test/routes/form.test.js
CAT-1248 update initial category decision page second time round for womens estate.
> Cat 1248 initial cat update the 2nd time around decision page so that it works for womens estate

- database_refresh/README.md
CAT-1401 updated README.md as cron job for database refresh runs on even weeks.
> CAT-1401 updated README.md with cron job info

- server/routes/form.js
- test/routes/form.test.js
- test/routes/recat.test.js
CAT-1226 removal of duplicate API call
> Cat 1226 remove unnecessary API call

- integration-tests/src/test/groovy/uk/gov/justice/digital/hmpps/cattool/pages/OpenConditionsAddedPage.groovy
- integration-tests/src/test/groovy/uk/gov/justice/digital/hmpps/cattool/specs/OpenConditionsSpecification.groovy
- integration-tests/src/test/groovy/uk/gov/justice/digital/hmpps/cattool/specs/ratings/OffendingHistorySpecification.groovy
- server/views/formPages/openConditions/furtherCharges.html
- server/views/pages/openConditionsAdded.html
- server/views/partials/reviewContentsOpenConditions.html
- server/views/partials/warningOffendingHistory.html
- test/routes/form.test.js
- test/routes/openConditions.test.js
Cat 1416 further chargers questions visible in cya page remove camel case from open conditions statement
> Cat 1416 further chargers questions visible in cya page remove camel case from open conditions statement

- server/views/formPages/recat/securityInput.html
CAT-1400 modification of recat security page to remove hint
> CAT-1400 modified recat security page

- helm_deploy/values-dev.yaml
Cat 1421 allow ip 194 33 192 3 access to dcs in dev envi
> Cat 1421 allow ip 194 33 192 3 access to dcs in dev envi

- integration-tests/src/test/groovy/uk/gov/justice/digital/hmpps/cattool/mockapis/RiskProfilerApi.groovy
- integration-tests/src/test/groovy/uk/gov/justice/digital/hmpps/cattool/model/TestFixture.groovy
- integration-tests/src/test/groovy/uk/gov/justice/digital/hmpps/cattool/specs/WomenEstateSpecification.groovy
- integration-tests/src/test/groovy/uk/gov/justice/digital/hmpps/cattool/specs/ratings/EscapeSpecification.groovy
CAT-1481-integrationtest for dont ask catb question on risk escape page
> CAT-1481-integrationtest for dont ask catb question on risk escape page

- integration-tests/src/test/groovy/uk/gov/justice/digital/hmpps/cattool/mockapis/RiskProfilerApi.groovy
- integration-tests/src/test/groovy/uk/gov/justice/digital/hmpps/cattool/model/TestFixture.groovy
- integration-tests/src/test/groovy/uk/gov/justice/digital/hmpps/cattool/specs/WomenEstateSpecification.groovy
- integration-tests/src/test/groovy/uk/gov/justice/digital/hmpps/cattool/specs/ratings/EscapeSpecification.groovy
- server/views/formPages/ratings/escapeRating.html
- test/routes/form.test.js
CAT-1481 do not ask the Cat B question on the risk of escape page
> CAT-1481 do not ask the Cat B question on the risk of escape page

- test/services/statsService.test.js
CAT-1402 womens initial cat stats page
> CAT-1402 womens initial cat stats page

- server/data/statsClient.js
- server/views/pages/dashboardInitial.html
- test/data/statsClient.test.js
Added conditional sections to dashboardInitial view and added specific query for female decisions section
> CAT-1480 Updates to the Women's initial cat stats page

- server/app.js
- server/views/accessibility-statement.html
- server/views/accessibilityStatement.html
- server/views/partials/layout.html
CAT-1430 add accessibility statement page and link in footer
> Cat 1430 a 11 y link to accessibility statement page

- jobs/dead-letter/clearDeadLetterQueuesWithExit.js
- server/index.js
- server/utils/azure-appinsights.js
- server/utils/azure-appinsights.test.js
SI-12-establishment-usage-tracking
> SI-12-establishment-usage-tracking

- .env.test
- integration-tests/src/test/groovy/uk/gov/justice/digital/hmpps/cattool/specs/LandingPageSpecification.groovy
- server/services/offendersService.js
- test/services/offenderService.test.js
* Adds in cat's T and R (Women's Open and Closed)
* Adds in unit tests for T & R as allowable categories
* Updates Groovy tests to the amended cat / recat journey for both
> [SI-164] Adds Fem Open / Closed to required cat type allowables

- server/services/offendersService.js
- test/services/offenderService.test.js
Fixes a bug whereby offenders were not showing up on a recat dashboard if their release date was after their next review date, but their recat had been rejected by the supervisor.
> [SI-264] Rejected recats display when next review is after release

- .circleci/config.yml
- docker-compose-test.yml
https://github.com/localstack/localstack/releases/tag/v3.0.0
> [SI-517] Updates localstack to v3

- .gitignore
- docker-compose-test.yml
- server/data/nomisClientBuilder.js
A prison-api endpoint needs to switch form auth token to client token
> SDIT-1410 UserResource use client token

- .circleci/config.yml
- docker-compose-test.yml
> [SI-679] Use latest Localstack

- helm_deploy/offender-categorisation/values.yaml
- server/config.js
- server/services/healthCheck.js
Add productId to the application and health check.
> SI-768_add_productid_to_values_yaml

- package-lock.json
- package.json
https://app.circleci.com/pipelines/github/ministryofjustice/offender-categorisation/3305/workflows/3893cd11-70fc-4a7c-8889-f27366b46130/jobs/15363
> [CHORE] Bump express to 4.19.2 to satisfy trivvy

- helm_deploy/values-dev.yaml
- helm_deploy/values-preprod.yaml
https://dsdmoj.atlassian.net/jira/software/c/projects/SI/boards/1188?selectedIssue=SI-926
> Changing the Preprod and Dev IP allowlists in helm values

- package-lock.json
- package.json
Link to ticket: https://dsdmoj.atlassian.net/browse/SI-662
> updated joi

- Dockerfile
As per https://mojdt.slack.com/archives/CH6D099DF/p1719829916313589
> Update Dockerfile to use new AWS certs.

- assets/js/govukInitialisation.js
- integration-tests/src/test/groovy/uk/gov/justice/digital/hmpps/cattool/specs/OpenConditionsSpecification.groovy
- integration-tests/src/test/groovy/uk/gov/justice/digital/hmpps/cattool/specs/recat/OpenConditionsSpecification.groovy
- server/views/pages/recategoriserHome.html
- server/views/partials/layout.html
After pushing the previous change, the role switcher was no longer working on the recategoriser home page since the script tag including the js for it was being overridden. Also there were js errors due to an inline script tag and an extra script which didn't need to be included.
Also added waitfors on a couple groovy tests that kept failing.
> Fix role switcher

- server/services/offendersService.js
hotfix for preprod error, tests to follow
```
11:00:41.421Z DEBUG Cat tool: getCategorisationRecords called for PVI, status STARTED,SECURITY_BACK,SUPERVISOR_BACK,SECURITY_AUTO,SECURITY_FLAGGED,SECURITY_MANUAL, type RECAT
11:00:41.466Z  INFO Cat tool:  (key="RecategoriserHome getDueRecats investigation", agencyId=PVI, numberFromNomis=45, numberFromDb=6, intersectionOfNomisAndDb=1)
11:00:41.467Z DEBUG Cat tool: end getPomMap
11:00:41.469Z DEBUG Cat tool: retrieving status APPROVED for booking id 2905477
11:00:41.469Z ERROR Cat tool: Error during getRecategoriseOffenders
TypeError: resultsU21.get is not a function
at /app/dist/server/services/offendersService.js:734:45
at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
at async Promise.all (index 0)
at async …
```
> [SI-607] Use u21 map object

- package-lock.json
- package.json
- server/data/dataAccess/db.js
Pre-requisite change, to enable testing of scripts on pre-prod before committing the full code.
> [SI-1206] Adds xlsx for spreadsheet output, db cert path update for same

- migrations/20241011073506_idx_form_by_offender_status_sequence.js
see https://dsdmoj.atlassian.net/browse/SI-1261
> [SI-1261] Add index for offender_no, status, sequence_no query

- assets/sass/local.sass
- server/services/recategorisation/filter/recategorisationFilter.ts
These changes were requested as part of the user testing by UX.
> Recat table width and order of filters

- server/data/risksAndNeeds/risksAndNeedsApi.ts
- server/middleware/featureFlagMiddleware.js
- server/routes/home.js
- server/services/recategorisation/filter/recategorisationFilter.ts
- test/middleware/featureFlagMiddleware.test.js
- test/routes/form.test.js
- test/routes/home.test.js
- test/routes/liteCategories.test.js
- test/routes/recat.test.js
- test/routes/utils/appSetup.js
This is to allow us to test the filter on production.
> Show prioritisation filter based on cookie or environment variable

- integration_tests/e2e/recat/openConditions.cy.ts
- integration_tests/pages/categoriser/base.ts
- integration_tests/pages/form/baseApprovedView.ts
- integration_tests/pages/form/supervisor/review.ts
Migration of this test
https://github.com/ministryofjustice/offender-categorisation/blob/main/integration-tests/src/test/groovy/uk/gov/justice/digital/hmpps/cattool/specs/recat/OpenConditionsSpecification.groovy#L364-L466
> [SI-1317] Migrate openConditions groovy test to cypress - third test only

- integration_tests/e2e/recat/openConditions.cy.ts
- integration_tests/mockApis/elite2.ts
- integration_tests/pages/categoriser/base.ts
- integration_tests/pages/form/baseApprovedView.ts
- integration_tests/pages/form/supervisor/message.ts
- integration_tests/pages/form/supervisor/review.ts
- integration_tests/pages/tasklistRecat/tasklistRecat.ts
- server/views/formPages/supervisor/supervisorMessage.html
Migrates this groovy test
https://github.com/ministryofjustice/offender-categorisation/blob/main/integration-tests/src/test/groovy/uk/gov/justice/digital/hmpps/cattool/specs/recat/OpenConditionsSpecification.groovy#L468-L626
> [SI-1317] migrate open conditions from groovy fourth test

- assets/sass/local.sass
- integration-tests/src/test/groovy/uk/gov/justice/digital/hmpps/cattool/model/TestFixture.groovy
- integration-tests/src/test/groovy/uk/gov/justice/digital/hmpps/cattool/specs/HomePageSpecification.groovy
- integration_tests/e2e/recategoriserHome.cy.ts
- integration_tests/support/utilities.ts
- server/services/offendersService.js
- server/views/pages/categoriserHome.html
- server/views/pages/recategoriserHome.html
- test/services/offenderService.test.js
Fix to show overdue on a new line
> Fix overdue text

- server/data/formClient.js
- server/utils/statusEnum.js
- test/data/formClient.test.js
https://dsdmoj.atlassian.net/browse/SI-1576
> fix for cancelled release records not being excluded

- assets/sass/_common.scss
- assets/sass/components/_feedback-tag.scss
- integration_tests/e2e/womensEstate.cy.ts
- integration_tests/pages/supervisor/home.ts
- integration_tests/pages/taskList/taskList.ts
- server/routes/home.js
- server/views/pages/categoriserHome.html
- server/views/pages/recategoriserHome.html
- server/views/pages/securityHome.html
- server/views/pages/supervisorHome.html
- server/views/pages/tasklist.html
- server/views/pages/tasklistRecat.html
- server/views/partials/smartSurveyTag.html
Adds a new banner which will alert users to a new survey specific to the women's rollout.
[SI-1702](https://dsdmoj.atlassian.net/jira/software/c/projects/SI/boards/1800?selectedIssue=SI-1702)
[SI-1702]: https://dsdmoj.atlassian.net/browse/SI-1702?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SI-1702: Add new survey banner to women's rollout pages

- server/views/formPages/supervisor/furtherInformation.html
> added in fix for recat decision being a different json shape from initial

- server/views/pages/categoriserLanding.html
- server/views/pages/liteApprove.html
- server/views/pages/liteCategories.html
- server/views/pages/liteCategoriesConfirmed.html
- server/views/pages/recategoriserLanding.html
Ticket: [SI-1811](https://dsdmoj.atlassian.net/jira/software/c/projects/SI/boards/1800?selectedIssue=SI-1811)
[SI-1811]: https://dsdmoj.atlassian.net/browse/SI-1811?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SI-1811: Update content in lite journey
