- server/views/formPages/categoriser/provisionalCategory.html
- server/views/formPages/ratings/escapeRating.html
- server/views/formPages/ratings/extremismRating.html
- server/views/formPages/ratings/offendingHistory.html
- server/views/formPages/ratings/securityBack.html
- server/views/formPages/ratings/securityInput.html
- server/views/formPages/ratings/violenceRating.html
- server/views/formPages/security/review.html
- server/views/formPages/supervisor/review.html
This PR just alerts the user when the textarea contains too much text. Ive set a limit of 50000 chars, with a count displayed when the contents goes over 50% of this.
The user can still post the form though (and if over about 80K the 'request entity too large' error will still occur), so not a complete solution.
> DC-197 request entity too large error: use character-count textareas

- integration-tests/src/test/groovy/uk/gov/justice/digital/hmpps/cattool/mockapis/OauthApi.groovy
- server/authentication/clientCredentials.js
- server/config.js
Actually it *was* escaped, but should not have been. Fixed in the same manner as NN etc.
Also switched from licences default client id to categorisationtool for in-memory use
> DC-207 The client api secret does not appear to be escaped

- integration-tests/src/test/groovy/uk/gov/justice/digital/hmpps/cattool/mockapis/Elite2Api.groovy
- server/data/nomisClientBuilder.js
- server/services/offendersService.js
- test/data/nomisClient.test.js
- test/services/offenderService.test.js
overriding page limit for initial u21 query
added flag to prevent 404 when prison is inactive
> Cat_425 new agency agnostic endpoint for u21 lookups

- integration-tests/src/test/groovy/uk/gov/justice/digital/hmpps/cattool/specs/ratings/OffendingHistorySpecification.groovy
- server/routes/form.js
- server/services/offendersService.js
- server/views/partials/warningOffendingHistory.html
- test/routes/recat.test.js
- test/routes/tasklistRecat.test.js
- test/services/offenderServiceGetCatAInformation.test.js
Fixed assuming a cat A could not occur during the current sentence, and also applied ordering (as endpoint cat history data is actually not ordered! )
> CAT-508 Cat A warning bug

- server/routes/form.js
- server/services/offendersService.js
- test/services/offenderService.test.js
Also filter duplicate agencies from the get-description calls
> CAT-609 Transaction incorrect order causes inconsistency during approve

- .circleci/config.yml
- README.md
Just some tidy up from the re-name. Needed these parameters as a workaround due to the orb assuming project name was deploy name.
> CAT-642: remove unneeded parameters in DPS orb

- integration-tests/src/test/groovy/uk/gov/justice/digital/hmpps/cattool/mockapis/RiskProfilerApi.groovy
- integration-tests/src/test/groovy/uk/gov/justice/digital/hmpps/cattool/model/TestFixture.groovy
- integration-tests/src/test/groovy/uk/gov/justice/digital/hmpps/cattool/pages/recat/RiskProfileChangeDetailPage.groovy
- integration-tests/src/test/groovy/uk/gov/justice/digital/hmpps/cattool/specs/HomePageSpecification.groovy
- integration-tests/src/test/groovy/uk/gov/justice/digital/hmpps/cattool/specs/LandingPageSpecification.groovy
- integration-tests/src/test/groovy/uk/gov/justice/digital/hmpps/cattool/specs/LiteSpecification.groovy
- integration-tests/src/test/groovy/uk/gov/justice/digital/hmpps/cattool/specs/OpenConditionsSpecification.groovy
- integration-tests/src/test/groovy/uk/gov/justice/digital/hmpps/cattool/specs/ProvisionalCategorySpecification.groovy
- integration-tests/src/test/groovy/uk/gov/justice/digital/hmpps/cattool/specs/ReviewSpecification.groovy
- integration-tests/src/test/groovy/uk/gov/justice/digital/hmpps/cattool/specs/SupervisorSpecification.groovy
- integration-tests/src/test/groovy/uk/gov/justice/digital/hmpps/cattool/specs/TasklistRecatSpecification.groovy
- integration-tests/src/test/groovy/uk/gov/justice/digital/hmpps/cattool/specs/TasklistSpecification.groovy
- integration-tests/src/test/groovy/uk/gov/justice/digital/hmpps/cattool/specs/ratings/SecurityInputSpecification.groovy
- integration-tests/src/test/groovy/uk/gov/justice/digital/hmpps/cattool/specs/recat/OpenConditionsSpecification.groovy
- integration-tests/src/test/groovy/uk/gov/justice/digital/hmpps/cattool/specs/recat/RiskChangeAlertDetailSpecification.groovy
- integration-tests/src/test/groovy/uk/gov/justice/digital/hmpps/cattool/specs/recat/SecurityInputSpecification.groovy
- server/routes/tasklist.js
- server/routes/tasklistRecat.js
- server/services/formService.js
- server/services/offendersService.js
- server/utils/functionalHelpers.js
- server/utils/riskChange.js
- server/views/formPages/recat/riskProfileChangeDetail.html
- test/routes/form.test.js
- test/routes/recat.test.js
- test/routes/tasklist.test.js
- test/routes/tasklistRecat.test.js
- test/services/formService.test.js
- test/services/sqsService.test.js
- test/utils/riskChange.test.js
Automatically refer to security, like SOC cases and remove from list generated by batch
Also align text of assaults in custody from batch with online version.
> CAT-679 Flag PF cases to security

- integration-tests/src/test/groovy/uk/gov/justice/digital/hmpps/cattool/pages/ReviewPage.groovy
- integration-tests/src/test/groovy/uk/gov/justice/digital/hmpps/cattool/pages/recat/ReviewRecatPage.groovy
- integration-tests/src/test/groovy/uk/gov/justice/digital/hmpps/cattool/specs/OpenConditionsSpecification.groovy
- integration-tests/src/test/groovy/uk/gov/justice/digital/hmpps/cattool/specs/recat/OpenConditionsSpecification.groovy
- test/routes/openConditions.test.js
- added int test for  https://dsdmoj.atlassian.net/browse/CAT-797 AC 5 for RECAT
- added unit tests for https://dsdmoj.atlassian.net/browse/CAT-797 AC 9 for both INITIAL and RECAT
- https://dsdmoj.atlassian.net/browse/CAT-1220 int tests are only for initial and recat CYA pages, but that is sufficient as the code changes is done in a partial
- https://dsdmoj.atlassian.net/browse/CAT-1223 modified selectors in existing integration test to cover AC
> CAT-1201 additional coverage for CAT-1180 epic

- server/views/formPages/recat/securityInput.html
- server/views/formPages/security/review.html
- server/views/partials/reviewContents.html
- server/views/partials/reviewContentsRecat.html
CAT-1400 hide security information on print out of cat/recat/supervisor review pages for every user.
> CAT-1400 no print out of security information

- assets/js/preventDoubleSubmit/index.js
- server/views/pages/liteCategories.html
Implementation only as tests are more involved, requiring unmerged Cypress work - draft PR https://github.com/ministryofjustice/offender-categorisation/pull/718
The Gov UK front end components already include a piece of functionality to avoid double submits. The button for lite category submission is annotated with that attribute - https://github.com/ministryofjustice/offender-categorisation/blob/main/server/views/pages/liteCategories.html#L121-L124
This existing functionality works by debouncing / rate limiting the clicks to a maximum of 1 per second.
The problem experienced is that during longer unresponsive periods, the end users are clicking the submit button multiple times whilst the form is still submitting, but at longer durations than 1 second between clicks. This then creates …
> [SI-108] Adds lite category button disabling JS - implementation only

- integration-tests/src/test/groovy/uk/gov/justice/digital/hmpps/cattool/specs/LandingPageSpecification.groovy
Ahead of the required behaviour change for SI-164, this change adds in tests that cover current Initial & Recat journey behaviour for Women's Open (T) and Closed (R) categories.
> [SI-164] Adds Groovy tests to cover existing behaviour for Womens Open and Closed cats

- server/services/offendersService.js
- server/utils/utils.js
- test/services/offenderService.test.js
- test/utils/utils.test.js
Fixes a bug whereby any reviews awaiting supervisor approval that have a review date after their release date would not display on the recat dashboard.
The rest is additional unit tests for everything touched by this journey that did not have tests.
> [CAT-1531] Display all pending recats waiting for supervisor approval

- helm_deploy/offender-categorisation/templates/dlq-job.yaml
Action Required from Service Teams - Kubernetes 1.25 Upgrade - Removing deprecated APIsAs part of the work to upgrade the Cloud Platform Kubernetes cluster from 1.24 to 1.25, a number of [deprecated APIs have to be removed](https://kubernetes.io/docs/reference/using-api/deprecation-guide/#v1-25) from the manifests used to create kubernetes resources. Your team should have seen warnings of these deprecations already when deploying these resources either manually or through the pipeline.Below is the list of deprecated APIs linking to the guide explaining the changes that your team must make[batch/v1beta1 API of CronJob](https://user-guide.cloud-platform.service.justice.gov.uk/documentation/other-topics/apiversion-changes-cronjob-k8s-1-25.html)
[autoscaling/v2beta1 API version of …
> SI-465-Switch-Cat-Tool-to-non-deprecated-APIs

- server/views/partials/layout.html
Fix the typo in `layout.html` that should say `if feComponents.jsIncludes` with an 's' on the end. JS currently not working in the app
> fix-feComponents-typo

- .circleci/config.yml
- helm_deploy/offender-categorisation/Chart.yaml
- helm_deploy/values-dev.yaml
- helm_deploy/values-preprod.yaml
- helm_deploy/values-prod.yaml
This PR migrates the project to use groups of IPs in their allowlist.
By referring to groups to IP addresses, we can centralize the definition of groups of ip addresses.
If these lists require changing in the future, we can change the definition once and future deploys across all services will automatically include these new IPs.
3 allowlist(s) have been detected that can be migrated.
The effect of applying this PR is as follows:
- The following groups will be applied: `internal`
- The size of the allowlist defined in this file will change: `12 => 5 (7 removed)`
The new Group membership will result in the following IPs being added to your allowlist by applying this PR:
- petty-france-wifi
The following IPs have been identified as unnecessary and will be removed by applying this PR:
- …
> Migrating project to use groups in allowlist

- Dockerfile
A hazard of not using a multi-stage build it seems
> [SI-489] Removes npm cache left over from build

- integration_tests/e2e/liteCategories.cy.ts
- server/services/offendersService.js
- test/services/offenderService.test.js
The aim of this PR is not to actually remove the prisoners, but to list those who _would_ be removed, once the results have been manually verified.
> [SI-607] Log out prisoner booking IDs assumed needing removing from lite_category table

- integration_tests/db/queries.ts
- integration_tests/e2e/liteCategories.cy.ts
- migrations/20240408071312_add_approved_category_comment_to_lite_category.js
- server/data/formClient.js
- server/services/formService.js
- server/services/offendersService.js
- test/services/offenderService.test.js
It was noticed that approvedCategoryComment wasn't being stored in the database, this PR adds a column to the lite category table to store this field alongside the other form data from that submit.
> SI 151 store approved category comment in db

- server/app.js
- server/errorHandler.js
Redirecting to the signout page when it is a 401 plus including a logout of auth when there is no user, taken from the way other apps in the estate are handling this.
> added in redirection to sign-out when getting a 401

- .circleci/config.yml
- .env.test
- cypress.config.ts
- docker-compose.yml
- feature.env
- integration_tests/e2e/events.cy.ts
- integration_tests/e2e/liteCategories.cy.ts
- integration_tests/events/index.ts
- integration_tests/fixtures/events/mensUnapprovedInitialCategorisationSeedData.ts
- integration_tests/fixtures/events/mensUnapprovedLiteCategorisationSeedData.ts
- integration_tests/fixtures/events/mensUnapprovedRecategorisationSeedData.ts
- integration_tests/index.d.ts
- integration_tests/support/commands.ts
- package-lock.json
- package.json
- server/config.js
- server/data/formClient.js
- server/services/formService.js
- server/services/sqsService.js
- server/utils/eventUtils.js
- test/data/formClient.test.js
- test/services/formService.test.js
- test/services/sqsService.test.js
- test/utils/eventUtils.test.js
Listen for Offender Release events. Delete any pending (not APPROVED or CANCELLED) cats, recats, and lite cats for the offender.
This is currently behind an inactive feature flag, and for the moment will only log what we would have deleted.
> [SI-1091] Delete pending cats on Offender Release event

- server/services/offendersService.js
- test/services/offenderService.test.js
https://dsdmoj.atlassian.net/browse/SI-1204
^ more detail in the ticket.
This adds more statuses to continue showing despite the next review date being beyond the release date.
> Don't filter out reviews with Security statuses when next review date is beyond the release date

- .circleci/config.yml
- .eslintrc.json
- .gitignore
- Dockerfile
- cypress.config.ts
- package-lock.json
- package.json
- server/app.js
- tsconfig.json
This PR adds typescript support into offender-categorisation and therefore also moves to serving the compiled assets from the dist folder.
> Adding typescript support

- server/data/healthCheck.js
- test/data/healthcheck.test.js
Implementation stolen from https://github.com/brianc/node-postgres/issues/3124#issuecomment-1958782624
Adds tests to check that.
Can also test locally by changing the query (https://github.com/ministryofjustice/offender-categorisation/compare/feature/SI-1260-timeout-health-endpoint-after-30-seconds-db-call?expand=1#diff-1c1a8c93ae110219d1bda8b4db7ba1be4fca1ee44905b31d8258af3a1b78afe4R15) to:
`SELECT pg_sleep(3000)`
and set `MAX_WAIT` (https://github.com/ministryofjustice/offender-categorisation/compare/feature/SI-1260-timeout-health-endpoint-after-30-seconds-db-call?expand=1#diff-1c1a8c93ae110219d1bda8b4db7ba1be4fca1ee44905b31d8258af3a1b78afe4R9) to 1000 or similar.
> [SI-1260] Timeout /health endpoint db check after 30 seconds

- server/data/risksAndNeeds/risksAndNeedsApi.ts
- server/services/recategorisation/filter/recategorisationFilter.ts
Improvements for performance:
- ordering the filters so that it will apply all filters which don't require more data to be loaded first, and using the filtered list of prisoners to load data for the further filters.
- increased the batch size of the rosh data so more will be done in parallel.
logging added:
- to see if it's using the cache for RoSH correctly
- to see how long it takes to complete the fetching of crns and full fetching of RoSH data
- to see how many crns have no RoSH level
> Added in logging and slight refactor to improve performance

- integration_tests/e2e/recat/openConditions.cy.ts
- integration_tests/pages/form/openConditions/earliestReleaseDate.ts
- integration_tests/pages/form/openConditions/foreignNational.ts
- integration_tests/pages/form/openConditions/furtherCharges.ts
- integration_tests/pages/form/openConditions/notRecommendedPage.ts
- integration_tests/pages/form/openConditions/riskLevels.ts
- integration_tests/pages/form/openConditions/riskOfSeriousHarm.ts
- integration_tests/pages/form/openConditions/victimContactScheme.ts
- integration_tests/pages/form/recat/decision/categoriserEscapePage.ts
- integration_tests/pages/form/recat/decision/categoriserFurtherChargesPage.ts
- integration_tests/pages/form/recat/decision/categoriserOffendingHistoryPage.ts
- integration_tests/pages/form/recat/decision/decisionPage.ts
- integration_tests/pages/form/recat/decision/extremismPage.ts
- integration_tests/pages/form/recat/decision/violencePage.ts
- integration_tests/pages/form/recat/reviewRecatPage.ts
- integration_tests/pages/openConditionsAdded.ts
- integration_tests/pages/page.ts
- integration_tests/pages/recategoriser/home.ts
- integration_tests/pages/tasklistRecat/tasklistRecat.ts
- integration_tests/support/utilities.ts
- package-lock.json
- package.json
- server/views/formPages/openConditions/earliestReleaseDate.html
- server/views/formPages/openConditions/furtherCharges.html
- server/views/formPages/openConditions/riskLevels.html
- server/views/formPages/openConditions/riskOfHarm.html
- tsconfig.json
There is no behaviour change here - yet.
This test aims to replicate all of this - https://github.com/ministryofjustice/offender-categorisation/blob/main/integration-tests/src/test/groovy/uk/gov/justice/digital/hmpps/cattool/specs/OpenConditionsSpecification.groovy#L41-L371
however, I have deliberately removed the two 'in test sub tests' where validation failures are tested. Those are to be added.
> [SI-1317] Migrate openConditions groovy test to cypress - first test only

- .circleci/config.yml
I need to test the outcome of an offender having a `null` return value for their `nextReviewDate` for a call to prison api. 
At present all offenders on the recat list will always have a `nextReviewDate`. We think that a possible solution to SI-607 is to `null` that date. However, that is a larger API change (outside our team) and may not work. This change is to allow a non-pipeline blocking test in PreProd only.
We specifically need to test this against two prisoners flagged via app support in PVI.
> [SI-1247] Allow deploy of develop to preprod

- integration_tests/e2e/recat/openConditions.cy.ts
- integration_tests/e2e/recategoriserHome.cy.ts
- integration_tests/mockApis/elite2.ts
- integration_tests/pages/form/baseApprovedView.ts
- integration_tests/pages/form/recat/decision/decisionPage.ts
- integration_tests/pages/form/recat/reviewRecatPage.ts
- integration_tests/pages/form/recatApprovedView.ts
- integration_tests/pages/form/supervisor/review.ts
- integration_tests/pages/recatAwaitingSupervisorApproval/awaitingApprovalView.ts
- integration_tests/pages/recategoriser/home.ts
- package-lock.json
- package.json
- server/views/formPages/supervisor/recatReview.html
It's large because what it migrates from is equally very large - https://github.com/ministryofjustice/offender-categorisation/blob/main/integration-tests/src/test/groovy/uk/gov/justice/digital/hmpps/cattool/specs/recat/OpenConditionsSpecification.groovy#L203-L362
> [SI-1317] Migrate openConditions groovy test to cypress - second test only

- server/utils/fieldValidation.js
- test/utils/fieldValidation.test.js
The validator was not allowing dates including leading 0s e.g. 01/01/2025. It should accept 01/01/2025 or 1/1/2025 (or any combination). The date validator uses joi which is quite rigid in how it validates date format, I considered using joi.alternatives to explicitly check against each possible format however this breaks the error messages. Therefore I opted for this solution which is unideal - it removes a leading 0 if it exists and any 0 after a / character within a string and then validates strictly against the format D/M/YYYY. So it will convert 01/01/2025 to 1/1/2025 before validating. It would also convert 01/01/07 to 1/1/7 which is invalid because of the format of the year (YYYY) anyway.
> Fix date formats

- server/data/prisonerSearch/prisonerSearch.dto.ts
- server/data/prisonerSearchApi.js
- server/services/offendersService.js
- server/services/recategorisation/prisonerSearch/recategorisationPrisonerSearch.dto.test-factory.ts
- server/services/recategorisation/prisonerSearch/recategorisationPrisonerSearch.dto.ts
We know that some are errors due to being on remand and some are errors due to being recalls but I want to see if the recall flag or the legal status will help us differentiate between the two so we can handle them correctly.
> Si 1471 add additional logging for error due cats

- integration_tests/e2e/recat/openConditions.cy.ts
- server/routes/openConditions.js
- test/routes/openConditions.test.js
The bug was introduced when another bug was fixed... the other bug was that when open conditions was cancelled from a review it was still showing in the check my answers section and would still be in SAR requests etc. Removing it from there broke this kick out page because the kick out page was still using the persisted open conditions section to decide which error message to show, I've changed it to use a query parameter instead.
> Fix for Si 1508 open conditions kick out page bug

- server/data/prisonerSearch/prisonerSearch.dto.ts
- server/routes/home.js
- server/services/offendersService.js
- test/services/offenderService.test.js
In order to test that we can filter out all legal status = REMAND prisoners I've created a new endpoint which shows the exact same as the other endpoint but without the REMAND prisoners, we can use this to also test future changes e.g. the recalls etc.
> Filtering remand prisoners out of the dashboard on a different view of the dashboard

- server/services/offendersService.js
- test/services/offenderService.test.js
Added in a check that assessment is not pending to function looking for only approved assessments. It was showing some rejected categorisations in the category history table because they have an evaluation date set, which then gets called approved date in prison API even though the assessment was never approved.
> Bug showing rejected categorisations in category history table

- server/services/recategorisation/recall/recategorisationRecallService.test.ts
- server/services/recategorisation/recall/recategorisationRecallService.ts
It was getting mixed up on temporary release / admissions e.g. if the prisoner went to a dentist, added in a filter so it would ignore the temporary (TAP) inward type.
> added in fix for recall changes still sometimes showing wrong recall date in dashboard

- integration_tests/e2e/liteCategories.cy.ts
- integration_tests/pages/liteCategories/liteCategories.ts
- server/routes/liteCategories.js
- server/utils/utils.js
- server/views/pages/liteCategories.html
- test/routes/liteCategories.test.js
- test/utils/utils.test.js
[Ticket](https://dsdmoj.atlassian.net/jira/software/c/projects/SI/boards/1800?selectedIssue=SI-1721)
Also changes the input to use the GDS date input component and updates the validation.
> SI-1721: Remove auto-population of date in other category assessment screen
